# _config.yml

# Site settings
title: Cub Scout Pack 25
description: >-
  Join Cub Scout Pack 25! Fun activities, outdoor adventures, and values-based programs for kids in grades K–5.
logo: "/assets/images/cub-scout-logo.png"
baseurl: "" # Leave empty if publishing to root (e.g., https://yourusername.github.io/)
url: "https://cflpack25.org"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Include/exclude settings
include:
  - assets/css/custom.css
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

atom_feed:
  hide: true

# Social (for SEO tag plugin)
social:
  name: Cub Scout Pack 25
  links:
    #- https://www.facebook.com/YourPack123
    - mailto:fortgatlinpack25@gmail.com

# Defaults for posts/pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author: "Cub Scout Pack 25"

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X
